version: '3.4'
services:
  cassandra:
    image: library/cassandra:3.11
    container_name: cassandra
    ports:
      - 9042:9042
    restart: always
    volumes:
    - ./cassandra:/var/lib/cassandra
  app:
    build: .
    image: gowebapp
    depends_on:
      - cassandra
    ports:
      - 8080:8080
    restart: always
    env_file:
      - appEnv.env
  myapp-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: gowebapp
    command: dockerize -wait tcp://cassandra:9042 -timeout 30s /bin/bash -c 'go test -v -tags integration'
    env_file:
      - appEnv.env
    depends_on:
      - cassandra
      - app
