version: '3'
services:
  cassandra:
    image: library/cassandra:3.11
    container_name: cassandra
    ports:
      - 9042:9042
    restart: always
    volumes:
    - ./cassandra:/var/lib/cassandra
  app:
    build: .
    image: gowebapp
    depends_on:
      - cassandra
    ports:
      - 8080:8080
    restart: always
    env_file:
      - appEnv.env
  myapp-test:
    image: gowebapp

    command: dockerize
      -wait tcp://db:5432 -wait tcp://myapp:8000 -timeout 10s
      bash -c "node db/init.js && yarn test"
#    command: bash -c 'while !</dev/tcp/cassandra/9042; do sleep 5; done; go test -run handlers_test.go'
##    command: dockerize
##      -wait tcp://cassandra:9042 -timeout 100s
##      bash -c 'go test handlers_test.go;'
    restart: always
    env_file:
      - appEnv.env
    depends_on:
      - cassandra
      - app
