version: '3'
services:
  cassandra:
    image: library/cassandra:3.11
    container_name: cassandra
    ports:
      - 9042:9042
    restart: always
    volumes:
    - ./cassandra:/var/lib/cassandra
  app:
    build: .
    image: gowebapp
    depends_on:
      - cassandra
    ports:
      - 8080:8080
    restart: always
    env_file:
      - appEnv.env
  myapp-test:
    image: gowebapp
#    command: bash -c 'while !</dev/tcp/cassandra/9042; do sleep 5; done; cqlsh cassandra -f initdb.sql;'
    command: dockerize
      -wait tcp://cassandra:9042 -wait tcp://app:8080 -timeout 10s
      bash -c "go run handlers_test.go"
    restart: always
    env_file:
      - appEnv.env
    depends_on:
      - app
      - cassandra
