version: '3'
services:
  cassandra:
    image: library/cassandra:3.11
    container_name: cassandra
    ports:
      - 9042:9042
    restart: always
    volumes:
    - ./cassandra:/var/lib/cassandra
  app:
    build: .
    image: gowebapp
    depends_on:
      - cassandra
    ports:
      - 8080:8080
    restart: always
    command: /bin/dockerize -wait tcp://cassandra:9042 -timeout 20s /bin/app
    env_file:
      - appEnv.env
  myapp-test:
    image: gowebapp
    command: /bin/dockerize -wait http://app:8080/api/message/sz.sawicki1@gmail.com -timeout 40s /bin/handlers_test
    env_file:
      - appEnv.env
    depends_on:
      - cassandra
      - app
